Repository mikey0000/PyMammotion, pull requests merged in 2024-09, with the labels that each got.

#61 Update blade height maximum limit in device configuration
  pymammotion/data/model/device_config.py
Labels: enhancement, Review effort [1-5]: 1

#60 Implement Stream Subscription Retrieval and Response Handling
  pymammotion/http/http.py
  pymammotion/mammotion/devices/mammotion.py
  tests/login_and_get_stream_token.py
Labels: enhancement, Review effort [1-5]: 4, tests

#62 Fix keyword inconsistency for knife height parameter
  pymammotion/mammotion/commands/messages/driver.py
Labels: Review effort [1-5]: 1, bug_fix

#63 Fix coroutine warning in remove_device method
  pymammotion/mammotion/devices/mammotion.py
Labels: Review effort [1-5]: 2, bug_fix
